### ISSUE TITLE
distutils.version.LooseVersion is deprecated

### ISSUE THREAD

**Issue by foreverhy** [panodata/grafana-client#122]
**Describe the bug**
Got an error
```python
File /home/ffy/workspace/PyProjects/venv/lib/python3.12/site-packages/grafana_client/elements/dashboard.py:1
----> 1 from distutils.version import LooseVersion
      3 from .base import Base
      6 class Dashboard(Base):

ModuleNotFoundError: No module named 'distutils'
```
while import grafana_client in python 3.12.
Based on [PEP386](https://peps.python.org/pep-0386/), distutils is deprecated and we may have some alternatives.

**To Reproduce**
1. python 3.12
2. import grafana_client

**Expected behavior**
```ModuleNotFoundError: No module named 'distutils'```

**Versions**

**Additional context**

**Comment by amotl** [comment]
Hi @foreverhy,

thank you for writing in and reporting this. We will address this on the next iteration, and patches are always welcome.

With kind regards,
Andreas.

**Comment by amotl** [comment]
When there are no objections, we will probably follow the same strategy like at [crate-python](https://github.com/crate/crate-python), by vendoring [`packaging.version`](https://github.com/pypa/packaging/blob/main/src/packaging/version.py).

- https://github.com/crate/crate-python/pull/513

**Comment by amotl** [comment]
Dear @foreverhy,

GH-123 removes the dependency on `distutils.version`, and uses [`verlib2`](https://pypi.org/project/verlib2/) instead.

With kind regards,
Andreas.
