### ISSUE TITLE
Service Account functionality 

### ISSUE THREAD

**Issue by einar-lanfranco** [panodata/grafana-client#137]
I develop some functions i need, its a parcial functionality but i could make a pull request if you want to.

I use this fork https://github.com/einar-lanfranco/grafana-client

**Comment by amotl** [comment]
Dear Einar,

thank you for writing in. Your contribution will be much appreciated.

With kind regards,
Andreas.

**Comment by einar-lanfranco** [comment]
PR Done! :D

**Comment by amotl** [comment]
Dear @einar-lanfranco and @feerbau,

grafana-client 3.11.0 has just been released, including your improvement. Thank you again.

With kind regards,
Andreas.

**Comment by amotl** [comment]
> What is yet missing, is the wrapper for [Update service account](https://grafana.com/docs/grafana/latest/developers/http_api/serviceaccount/#update-service-account).

GH-165 has a corresponding improvement.

**Comment by amotl** [comment]
Corresponding enhancements have been included in grafana-client 4.0.0. Please let us know if they improve the situation for you.

**Comment by chintal** [comment]
I've used service accounts in 4.0+. No noticeable issues.

**Comment by amotl** [comment]
Thank you. Closing.
