### ISSUE TITLE
Could the proxies argument be added to the GrafanaApi?

### ISSUE THREAD

**Issue by fer-tovar** [panodata/grafana-client#14]
Basically as the title says. As im working under proxcies, I need this argument to be able to use requests, otherwise I get connection errors.

**Comment by amotl** [comment]
Dear @fer-tovar,

thank you for writing in. Can you try the suggestion outlined at [^1]:

> On Linux you can also do this via the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, like:
>
>     export HTTP_PROXY=10.10.1.10:3128
>     export HTTPS_PROXY=10.10.1.11:1080

I just verified it also works on macOS.

With kind regards,
Andreas.

[^1]: https://stackoverflow.com/a/8287752
[^2]: https://stackoverflow.com/a/16311657

**Comment by fer-tovar** [comment]
Hello @amotl 

I tried it, but the http request is still giving me connection errors, as if the proxy was not specified.

The requests.post only gives a response if the proxies are specified within the command, but if the proxies are not specified or they are specified outside the command, like it was suggested, then a response is not obtained.

My guess is that the same is happening with the grafana api's and the proxies should be specified inside the command, so they are passed to the requests commands.

**Comment by fer-tovar** [comment]
Nevermind, I had some problems in my code, but the solution of setting up the proxies outside the requests command worked perfectly. Thank you so much for your help.
