### ISSUE TITLE
New version of Grafana API create-annotation adds dashboardUID field

### ISSUE THREAD

**Issue by IBUMBLEBEE** [panodata/grafana-client#140]
**What API call you use?**
Annotations.add_annotation()

**What is the actual output?**
TypeError: Annotations.add_annotation() got an unexpected keyword argument 'dashboard_uid'

**What is the expected output?**
https://grafana.com/docs/grafana/latest/http_api/annotations/#create-annotation

**Comment by amotl** [comment]
Dear @IBUMBLEBEE,

thank you for writing in. It is really a bummer, it looks like [add_annotation](https://github.com/panodata/grafana-client/blob/3.10.0/grafana_client/elements/annotations.py#L78-L111) does not support the `dashboard_uid` argument, yet.

Will you be able to submit a patch to fix that, or do you want us to do it?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @IBUMBLEBEE,

grafana-client 3.11.0 has just been released, including a corresponding bugfix. Thank you again.

With kind regards,
Andreas.
