### ISSUE TITLE
Grafana 10.2.3: breaking changes

### ISSUE THREAD

**Issue by hamelg** [panodata/grafana-client#147]
**Describe the bug**

Grafana-client is no longer compatible with the data source permissions APIs of grafana Enterprise 10.2.3.

https://grafana.com/blog/2024/01/08/grafana-10.2.3-release-new-features-and-breaking-changes

The following data source permission endpoints have been removed:
 
- GET /datasources/:datasourceId/permissions
- POST /api/datasources/:datasourceId/permissions
- DELETE /datasources/:datasourceId/permissions
- POST /datasources/:datasourceId/enable-permissions
- POST /datasources/:datasourceId/disable-permissions

replaced by:

- GET /api/access-control/datasources/:uid for listing data source permissions
- POST /api/access-control/datasources/:uid/users/:id, POST /api/access-control/datasources/:uid/teams/:id
- POST /api/access-control/datasources/:uid/buildInRoles/:id for adding or removing data source permissions

**Versions**
- Grafana: 10.2.3
- `grafana-client`: 3.11.0

**Comment by amotl** [comment]
Dear Gilles,

thank you for your report.

a) I guess it will be similar with Grafana OSS. Do you have any information about this?
b) Do you think it will be a good measure to add the corresponding implementations to [rbac.py](https://github.com/panodata/grafana-client/blob/3.11.0/grafana_client/elements/rbac.py) contributed by you the other day on behalf of GH-60?

With kind regards,
Andreas.

**Comment by hamelg** [comment]
Hello Andreas,

This change only affects the enterprise version, as data source permissions are only available in Grafana Enterprise [1].

I agree with your plan :

- Keep deprecated API for backwards compatibility for grafana Enterprise <10.2.3.
- Add the new implementation to the existing subset of the RBAC APIs for grafana Enterprise >=10.2.3.

I'm adding this task to my to-do list.

[1]  https://grafana.com/docs/grafana/latest/developers/http_api/datasource_permissions/

**Comment by amotl** [comment]
Thank you very much for your assessment, and your quick reply. If you could support the project by submitting the pull request yourself, it will be great!

**Comment by amotl** [comment]
Hi again. Thanks for your support by submitting GH-152 and GH-156. [grafana-client](https://pypi.org/project/grafana-client/) 3.11.2 has been released, including your changes. Do you think this issue can be closed?

**Comment by hamelg** [comment]
Yes, thank you. I close it.
