### ISSUE TITLE
Missing parentUid for create_folder

### ISSUE THREAD

**Issue by grafuls** [panodata/grafana-client#160]
**What Grafana API endpoint the library is missing?**
Not an endpoint as such but a parameter on the `create_folder` method to include `parentUid` for those using nested folders.

**Additional Info**
https://grafana.com/docs/grafana/latest/developers/http_api/folder/#create-folder

**Comment by amotl** [comment]
Hi Gonzalo, thanks for reporting. Would you be able to submit a corresponding patch to improve the situation?

**Comment by grafuls** [comment]
sure can

**Comment by amotl** [comment]
GH-164 has corresponding improvements.

**Comment by amotl** [comment]
Corresponding enhancements have been included in grafana-client 4.0.0. Please let us know if they improve the situation for you.

**Comment by chintal** [comment]
I've used 4.0+ for creating nesting folders. All the things I've tried seem to working. I think you can call this done. If a specific issue presents itself in the future, a separate issue can be reported.

**Comment by amotl** [comment]
Thank you again. Also closing this one.
