### ISSUE TITLE
Version 4.0.0: `TypeError: expected string or bytes-like object`

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-client#169]
## Problem
```
E       TypeError: expected string or bytes-like object
```
-- https://github.com/panodata/grafana-wtf/actions/runs/8482124688/job/23240743427?pr=125#step:5:510

## References
- https://github.com/panodata/grafana-wtf/pull/125

## Thoughts
Maybe Niquests returns bytes, where Requests previously returned text?

/cc @Ousret

**Comment by amotl** [comment]
In response to this hiccup, we just yanked the release '4.0.0' from PyPI again.

**Comment by amotl** [comment]
There is also:

```python
AttributeError("'Version' object has no attribute '_version'")
```

**Comment by amotl** [comment]
What about this guy?

```
ERROR    grafana_wtf.core:core.py:317 Request to /health endpoint failed: send() got an unexpected keyword argument 'on_post_connection'
```

```python
        # Send the request
>       r = adapter.send(request, **kwargs)
E       TypeError: send() got an unexpected keyword argument 'on_post_connection'
```

-- https://github.com/panodata/grafana-wtf/actions/runs/8482124688/job/23240743427?pr=125#step:5:233

**Comment by amotl** [comment]
```python
import grafana_client
from verlib2 import Version


if __name__ == "__main__":

    gc = grafana_client.GrafanaApi(host="play.grafana.com")

    print(gc.version)
    print(Version(gc.version))

    path = "/health"
    response = gc.client.GET(path)
    print(response, type(response))
```

```
$ python testme.py
11.1.0-68793
11.1.0.post68793
{'commit': 'df39fc54a6a7586e6da55270bdd4ca9d4d687e2b', 'database': 'ok', 'enterpriseCommit': '6543ac51c17e69bd6ac3c8ad6bbdcf3d3037802c', 'version': '11.1.0-68793'} <class 'dict'>
```

**Comment by Ousret** [comment]
The faulty part is this for the "on_post_connection" error https://github.com/panodata/grafana-wtf/blob/6dd8b91a4372fd2f0e2681f901b5724e2c084755/grafana_wtf/core.py#L110
you need to patch it to inject a proper HTTPAdapter from niquests.

**Comment by Ousret** [comment]
I guess, the whole thing is linked to the hybrid niquests/requests adapters. so, after cleaning this up, all will work fine.

And you don't need to do `pool_connections=100, pool_maxsize=100, max_retries=5,` in the HTTPAdapter anymore, it can be set within the Session constructor, 

so instead of

```python
adapter = requests.adapters.HTTPAdapter(pool_connections=100, pool_maxsize=100, max_retries=5, pool_block=True)
self.grafana.client.s.mount("http://", adapter)
self.grafana.client.s.mount("https://", adapter)

return self
```

do

```python
self.grafana.client.s = Session(pool_connections=100, pool_maxsize=100, retries=5)

return self
```

**Comment by amotl** [comment]
So that's clearly my fault on grafana-wtf, where I wrongly verified success beforehand. So, effectively, the release would not need to have been yanked, so we un-yanked it again. Enjoy, and thanks for your support.

**Comment by Ousret** [comment]
No worries. I understand,
Look at the previous comment, for guidance on how you can increase the pool scale properly without handling HTTPAdapter anymore.
