### ISSUE TITLE
Unable to create team

### ISSUE THREAD

**Issue by ricmano** [panodata/grafana-client#17]
**Describe the bug**
When using `grafana_api.teams.add_team()`, I am observing errors.

**To Reproduce**

1. Create Grafana Api client
2. Search team (not found)
3. Create team
4. Call `add_team` method
5. See error - `grafana_client.client.GrafanaClientError: Client Error 404: Not found`
    ```python
    grafana_api = GrafanaApi(auth=GRAFANA_API_KEY, host=GRAFANA_URL)
    grafana_teams = grafana_api.teams.search_teams(perpage=100, page=1, query=team_name)

    grafana_team = next((team for team in grafana_teams if team["name"] == team_name), None)

    if grafana_team is None:
      team = {
          "name": team_name
          }
      new_team = grafana_api.teams.add_team(json.dumps(team))
    ```

**Expected behavior**
We should be able to create a team in grafana.

**Versions**
- Grafana: [ 8.4.5]
- `grafana-client`: [ 2.3.0]
- Authentication: Token

**Additional context**
If I call the same endpoint using postman I'm able to create the team

**Comment by amotl** [comment]
Dear Ricardo,

thank you very much for writing in and reporting this flaw. Do you see any chance to dive into the code, see what is going wrong, fix it and submit a patch? That would be grand!

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Ricardo,

I've just added an example program at [examples/team.py] and verified it works for me on a local Grafana 8.4.4 installation. When running it like `python examples/team.py`, the output is:
```
Health check
{'commit': 'fcfb01faeb', 'database': 'ok', 'version': '8.4.4'}
Create team
{'message': 'Team created', 'teamId': 3}
Search teams
[
  {
    "id": 3,
    "orgId": 1,
    "name": "Testdrive Team",
    "email": "email@example.org",
    "avatarUrl": "/avatar/8fbf4bd0581c9ccc67c560dea9931a1b",
    "memberCount": 0,
    "permission": 0,
    "accessControl": null
  }
]
```


Can you also give it a try on your end and report back?

With kind regards,
Andreas.

[examples/team.py]: https://github.com/panodata/grafana-client/blob/main/examples/team.py

**Comment by amotl** [comment]
Ah, now I am seeing it. You are calling
```
grafana_api.teams.add_team(json.dumps(team))
```
but you should be calling it like
```
grafana_api.teams.add_team(team)
```
instead.

**Comment by amotl** [comment]
Dear Ricardo,

28359d253 makes the library croak with a corresponding exception when putting the wrong type of data into the API wrapper methods. We hope this will improve the user convenience in such situations.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Ricardo,

have you been able to check if my suggestion at https://github.com/panodata/grafana-client/issues/17#issuecomment-1159598505 resolves the problem for you?

With kind regards,
Andreas.

**Comment by ricmano** [comment]
Hi Andreas, Not yet, I'll try during next week, thank you for the quick replies

**Comment by ricmano** [comment]
Hello Andreas,

Sorry for the delay, I confirm that it is working.

Once again thanks for the correction.

Best regards
Ricardo Mano
