### ISSUE TITLE
Dashboard Search API endpoint is incorrect

### ISSUE THREAD

**Issue by chintal** [panodata/grafana-client#174]
The `search.search_dashboards` endpoint has incomplete / incorrect parameters. 

See https://grafana.com/docs/grafana/latest/developers/http_api/folder_dashboard_search/

The following parameters are missing:
 - dashboardUids
 - folderUids

The following parameters are included but aren't supported by the current API:
 - folderIds 

**Versions**

-  Grafana: v10.4.1 (d3ce857c0e)
-  grafana-client: git main head (4.0.1)
-  Authentication: Token

**Comment by amotl** [comment]
Dear Chintalagiri,

thank you so much for discovering that flaw. It clearly demonstrates once again that grafana-client needs an integration test suite.

- GH-50

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again. Thank you very much for fixing this with d341a2b08d on behalf of GH-172.
