### ISSUE TITLE
Cannot find find_url function in GrafanaApi class in api.py module

### ISSUE THREAD

**Issue by achin-netskope** [panodata/grafana-client#26]
**Describe the bug**
I see this 
`AttributeError: type object 'GrafanaApi' has no attribute 'from_url'` 

**To Reproduce**

1. Install latest grafana-client using `pip install grafana-client==2.3.0` 

2. Run with valid key
```
from grafana_client import GrafanaApi

# Use Grafana API token.
grafana = GrafanaApi.from_url(
    url="https://grafana.example.org/grafana",
    auth="eyJrIjoiWHg...dGJpZCI6MX0=",
)
```

**Expected behavior**
I see the method in the repo code but not in my site packages when I do pip install.
Expecting this to run error free.

**Versions**
- Grafana: [ 8.5.2]
- `grafana-client`: [ 2.3.0]
- Authentication:  [Token]

**Additional context**

**Comment by achin-netskope** [comment]
My bad. On checking further, it seems that the `from_url` is to be released in 2.4.0.
I will close this and follow instructions here https://pypi.org/project/grafana-client/

**Comment by amotl** [comment]
Dear Achin,

you are right, `grafana-client==2.4.0` is around the corner. In the meanwhile, you can install the development version of the package into your sandbox by using `pip install --upgrade git+https://github.com/panodata/grafana-client`.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Achin,

`grafana-client==3.0.0` has been released. With this release, you will be able to use the new factory methods `GrafanaApi.from_url()` and `GrafanaApi.from_env()`.

With kind regards,
Andreas.
