### ISSUE TITLE
Missing update datasource by UID.

### ISSUE THREAD

**Issue by mgreen-sm** [panodata/grafana-client#33]
**What Grafana API endpoint the library is missing?**

There is no `update_datasource_by_uid` function, only `update_datasource`, which takes the ID rather than UID. Using the ID is deprecated.

See [Update an existing data source](https://grafana.com/docs/grafana/v9.0/developers/http_api/data_source/#update-an-existing-data-source) Grafana API documentation.

Quick work-around until implemented:

```python
  update_datasource = f"/datasources/uid/{uid}"
  grafana.client.PUT(update_datasource, json=datasource)
```

**Comment by amotl** [comment]
Dear Michael,

thanks for your suggestion. It got implemented with #36 and will be part of the next release.

With kind regards,
Andreas.
