### ISSUE TITLE
What about Preferences API

### ISSUE THREAD

**Issue by autokilla47** [panodata/grafana-client#42]
Grafana has User and Org Preferences API:
https://grafana.com/docs/grafana/latest/developers/http_api/preferences/ 
Couldn't find anything suitable. For example, how to set the default dashboard (homeDashboard) for an organization or a specific user. 
Are there any plans?

**Comment by amotl** [comment]
Dear @autokilla47,

thank you for writing in.

It looks like [1] has the corresponding implementation to retrieve and adjust "organization" preferences. However, it also looks like the corresponding API wrappers is missing for "users", at [2].

Would you feel confident enough to fill the gap and submit a corresponding patch? It will be very much appreciated.

With kind regards,
Andreas.

[1] https://github.com/panodata/grafana-client/blob/3.1.0/grafana_client/elements/organization.py#L179-L204
[2] https://github.com/panodata/grafana-client/blob/3.1.0/grafana_client/elements/user.py

**Comment by amotl** [comment]
I also see that `organization_preference_update` still uses the dashboard id [3], whereas today it should probably use the dashboard uid instead?

[3] https://github.com/panodata/grafana-client/blob/3.1.0/grafana_client/elements/organization.py#L200

**Comment by amotl** [comment]
Indeed. The correct payload would be:
```json
{
  "theme": "",
  "homeDashboardUID":"home",
  "timezone":"utc"
}
```

-- https://grafana.com/docs/grafana/latest/developers/http_api/preferences/#update-current-org-prefs

**Comment by amotl** [comment]
I've just exercised it. Apparently, sending `homeDashboardUID` to both the _Patch Current User Prefs_ and _Patch Current Org Prefs_ API endpoints will only work on Grafana 9. Before, `homeDashboardId` must be used. However, using `homeDashboardId` is still supported by Grafana 9.

**Comment by amotl** [comment]
Hi again,

on this matter, I've improved the situation with #51, which has been released with grafana-client 3.4.0. Feedback is very much appreciated.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi @autokilla47,

have you been able to test the new methods successfully?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I think it is safe to close this issue. Please let me know if you find any things to be improved on this matter.

With kind regards,
Andreas.
