### ISSUE TITLE
Need support for following missing api

### ISSUE THREAD

**Issue by harish422** [panodata/grafana-client#89]
1) Need "get_alertrule" api without need for an "alertrule_uid" as an argument
seems like this api support was added in 9.4

GET /api/v1/provisioning/alert-rules
https://github.com/panodata/grafana-client/blob/main/grafana_client/elements/alertingprovisioning.py#L9-L17

**Comment by amotl** [comment]
Dear @harish422,

thank you for writing in. We will add this on the next development iteration. On the other hand, patches are always welcome.

With kind regards,
Andreas.

**Comment by harish422** [comment]
@amotl  Hi,

I didn't know I had access. nvm, I submitted the api. Can you please review and merge if you can ?

Thanks,
Harish

**Comment by amotl** [comment]
Thank you very much, your improvement has been released with 3.6.0.

**Comment by amotl** [comment]
Hi again. I think it will be safe to close this issue. Thanks again for your contribution!
