### ISSUE TITLE
Dashboard.get_dashboard_by_name seems broken

### ISSUE THREAD

**Issue by oz123** [panodata/grafana-client#92]
**Describe the bug**

I might be totaly wrong by it seems this path this method tries to access does not exist.
At least not in the grafana docs..

```
  10  -> grafana.search.search_dashboards(tag="fake")                                                                                                                                                                                         
(Pdb++) grafana.search.search_dashboards(tag="fake")
[{'id': 1, 'uid': 'b071f222-28cf-4025-a13c-14b4adde3071', 'title': 'Palette-Fake', 'uri': 'db/palette-fake', 'url': '/d/b071f222-28cf-4025-a13c-14b4adde3071/palette-fake', 'slug': '', 'type': 'dash-db', 'tags': ['fake'], 'isStarred': False, 'sortMeta': 0}]
(Pdb++) grafana.dashboard.
client                        get_dashboard                 get_dashboard_permissions     get_home_dashboard            update_dashboard_permissions  
delete_dashboard              get_dashboard_by_name         get_dashboards_tags           update_dashboard              
(Pdb++) grafana.dashboard.get_dashboard_by_name("palette-fake")
*** grafana_client.client.GrafanaClientError: Client Error 404: Not found
Traceback (most recent call last):
  File "/home/oznt/.local/share/virtualenvs/reporting-JW0JCX-S/lib/python3.11/site-packages/grafana_client/elements/dashboard.py", line 26, in get_dashboard_by_name
    r = self.client.GET(get_dashboard_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oznt/.local/share/virtualenvs/reporting-JW0JCX-S/lib/python3.11/site-packages/grafana_client/client.py", line 156, in __request_runner
    raise GrafanaClientError(

```

**Versions**
- Grafana: 9.1.0
- `grafana-client`: 3.5.0
- Authentication: Token.

**Comment by amotl** [comment]
Hi Oz,

thank you for writing in.

> I might be totaly wrong by it seems this path this method tries to access does not exist.

Another option would be that the addressed dashboard just does not exist, right?

With kind regards,
Andreas.

**Comment by oz123** [comment]
In that case, the API isn't clear what is the dashboard name, is it the title? Is it case sensitive?

**Comment by amotl** [comment]
Getting a dashboard by slug has been deprecated [^1]. Today, with recent versions of Grafana, getting a dashboard by uid seems to be the only viable option [^2]. An alternative could be the Folder/Dashboard Search API [^3].

[^1]: https://grafana.com/docs/grafana/v7.5/http_api/dashboard/#get-dashboard-by-slug
[^2]: https://grafana.com/docs/grafana/v7.5/http_api/dashboard/#get-dashboard-by-uid
[^3]: https://grafana.com/docs/grafana/v7.5/http_api/folder_dashboard_search/

**Comment by amotl** [comment]
Dear Oz,

GH-109 will bring in a patch which avoids letting the user run into "404 Not Found" responses, but raise a corresponding exception instead.

With kind regards,
Andreas.

**Comment by oz123** [comment]
I appreciate your effort! Maintaining FOSS is hard (especially if done in your free time).
